USE [master]
GO

/****** Object:  Database [Blog]    Script Date: 12.05.2017 18:07:55 ******/
CREATE DATABASE [Blog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Blog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\Blog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Blog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\Blog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Blog] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Blog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Blog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Blog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Blog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Blog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Blog] SET ARITHABORT OFF 
GO

ALTER DATABASE [Blog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Blog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Blog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Blog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Blog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Blog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Blog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Blog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Blog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Blog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Blog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Blog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Blog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Blog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Blog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Blog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Blog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Blog] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Blog] SET  MULTI_USER 
GO

ALTER DATABASE [Blog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Blog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Blog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Blog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Blog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Blog] SET QUERY_STORE = OFF
GO

USE [Blog]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Blog] SET  READ_WRITE 
GO


